sudo: required
language: generic
services:
  - docker

before_install:
  -  docker build -t shivapotu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shivapotu/docker-react npm run test